name: Deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main # Set a branch to deploy from

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v2
        with:
          ruby-version: '3.x' # Or your preferred Ruby version
          bundler-cache: true # runs bundle install and caches installed gems automatically
      - name: Build Jekyll site
        run: bundle exec jekyll build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./_site
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
